export default defineEventHandler(() => {
    return [
        {
            id: 1,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "android",
            description: "best device",
            price: 100,
        },
        {
            id: 2,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 140,
        },
        {
            id: 3,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 4,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 250,
        },
        {
            id: 5,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 6,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 7,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 8,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 9,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 10,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 11,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
        {
            id: 12,
            url: "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
            name: "iphone",
            description: "best device",
            price: 200,
        },
    ]
})
